data:
	gcc -Wall -Wextra -pedantic main.c -o zad2
	./zad2 data

sender:
	gcc -Wall -Wextra -pedantic main.c -o zad2
	./zad2 nadawca

three:
	gcc -Wall -Wextra -pedantic main.c -o zad2
	./zad2 example@egxample.com topic "tekst to be send"

pedantic:
	gcc -Wall -Wextra -pedantic -Werror main.c -o zad2
