one:
	gcc -Wall -Wextra -pedantic main.c -o zad2
	./zad2 1

two:
	gcc -Wall -Wextra -pedantic main.c -o zad2
	./zad2 example@egxample.com topic "tekst to be send"
pedantic:
	gcc -Wall -Wextra -pedantic main.c -o zad2